---
- name: create public key file
  copy: src="~/.ssh/id_rsa.pub"
        dest="/home/vagrant/.ssh/id_rsa.pub"
        mode=0644

- name: create private key file
  copy: src="~/.ssh/id_rsa"
        dest="/home/vagrant/.ssh/id_rsa"
        mode=0600

# this looks frightening
- name: put public key into authorized keys
  shell: echo ~/.ssh/id_rsa.pub | grep -xq ~/.ssh/id_rsa.pub /home/vagrant/.ssh/authorized_keys || echo ~/.ssh/id_rsa.pub | tee -a /home/vagrant/.ssh/authorized_keys
