---
- name: download and unarchive phpmyadmin
  unarchive: src=https://files.phpmyadmin.net/phpMyAdmin/4.5.0.2/phpMyAdmin-4.5.0.2-english.tar.bz2 dest=/var/www/html/phpmyadmin

- name: make config out of sample
  shell: mv config.sample.inc.php config.inc.php chdir=/var/www/html/phpmyadmin

- name: add credentials into config
  blockinfile: |
    dest=/var/www/html/phpmyadmin/config.inc.php backup=yes
    content="$cfg['Servers'][$i]['auth_type'] = 'config'
        $cfg['Servers'][$i]['user'] = 'root'
        $cfg['Servers'][$i]['password'] = 'root'"