---
- name: set correct mode to public key file
  copy: src="/home/vagrant/keys/id_rsa.pub"
        dest="/home/vagrant/.ssh/id_rsa.pub"
        mode=0644
        owner=vagrant

- name: ensure correct rights of private key file
  copy: src="/home/vagrant/keys/id_rsa"
        dest="/home/vagrant/.ssh/id_rsa"
        mode=0600
        owner=vagrant

- name: adds rsa identities to the authentication agent
  sudo: no
  shell: 'eval `ssh-agent -s` && ssh-add /home/vagrant/.ssh/id_rsa'

- name: create private key file
  file: path="/home/vagrant/.ssh/id_rsa" mode=0600 owner=vagrant