---
- name: download and install composer into the target directory.
  get_url:
    url=https://getcomposer.org/composer.phar
    dest=/usr/local/bin/composer
    mode=0755

- name: increase composer timeout
  command: '/usr/local/bin/composer config --global process-timeout 3000'

- name: install dependiencies with composer
  composer: command=install working_dir={{myz_source_path}}/source
  sudo: no