---
- stat: path=/opt/myzanichelli_source_v2/.git
  register: gitdir

- name: check for changes
  command: git status chdir=/opt/myzanichelli_source_v2
  register: result
  when: gitdir.stat.exists == true

- name: setup the git repo
  git: repo={{item.value.repo}}
       version=develop
       dest={{apps_dir}}/{{item.value.dir}}
       accept_hostkey=True
       key_file="/home/vagrant/.ssh/id_rsa"
  with_dict: apps
  when: (gitdir.stat.exists == false) or (result.stdout_lines.1 == "nothing to commit, working directory clean")