---
- name: change google.repo file rights
  file:
    path: /etc/yum.repos.d/google.repo
    state: touch
    mode: "u+rw,g-wx,o-rwx"

- name: enable google yum repository
  blockinfile: |
    dest=/etc/yum.repos.d/google.repo
    force=yes
    content="[google64]
        name=Google - x86_64
        baseurl=http://dl.google.com/linux/rpm/stable/x86_64
        enabled=1
        gpgcheck=1
        gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub"

- name: install google chrome
  yum: name=google-chrome-stable state=present

- name: change file rights
  file:
    path: /usr/local/share/chromedriver
    state: directory
    mode: 0755

- name: download chrome driver
  connection: local
  get_url:
    url: http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
    dest: /usr/local/share/chromedriver
    force: no

- name: create simlink to chrome driver
  file:
    src: /usr/local/share/chromedriver
    dest: /usr/bin/chromedriver
    state: link

- name: create simlink to chrome driver
  file:
    src: /usr/local/share/chromedriver
    dest: /usr/local/bin/chromedriver
    state: link
  environment:
    PATH: "/usr/bin/chromedriver:{{ ansible_env.PATH }}"