---
- stat: path=/etc/yum.repos.d/google.repo
  register: config

- name: create google repo config
  template: src=google.repo.j2 dest=/etc/yum.repos.d/google.repo mode=0644
  when: config.stat.exists == false

- name: install google chrome
  yum: name=google-chrome-stable state=present

- name: download chrome driver
  command: 'wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip chdir=/tmp'

- name: unarchive chrome driver
  unarchive:
    src: /tmp/chromedriver_linux64.zip
    dest: /tmp

- name: move chrome driver to /usr/bin
  command: mv /tmp/chromedriver /usr/bin/chromedriver

- name: change chromedriver rights
  file:
    path: /usr/bin/chromedriver
    mode: 0755
  environment:
    PATH: "/usr/bin/chromedriver:{{ ansible_env.PATH }}"
