---
- name: check desktop installed
  shell: yum list installed | grep xorg | wc -l
  register: result

- name: install desktop
  shell: yum --disablerepo=epel install @xfce
  when: result.stdout == "0"

- name: start desktop
  shell: startxfce4 &