---
- stat: path=/opt/selenium-server-standalone-2.48.2.jar
  register: selenium

- name: download selenium
  command: 'wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar chdir=/opt'
  when: selenium.stat.exists == false