---
- name: ensure apache is installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - httpd-devel
    - mod_ssl
    - openssh

- name: add default apache host
  template:
    src: "000-default.conf.j2"
    dest: "/etc/httpd/conf.d/000-default.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: ensure apache is always running
  service:
    name: httpd
    state: started
    enabled: yes