---
- stat: path=/home/vagrant/.nvm
  register: p

- git: repo=https://github.com/creationix/nvm.git
    dest=/home/vagrant/.nvm
    accept_hostkey=true
    clone=yes
  when: p.stat.exists == false

- file: path=/home/vagrant/.nvm state=directory mode=0777

- stat: path=/home/vagrant/.nvm/.git
  register: p

#- debug: var=p

- git: repo=https://github.com/creationix/nvm.git
    dest=/home/vagrant/.nvm
    accept_hostkey=true
    update=yes
    version=v0.26.1
  when: p.stat.exists == true

- lineinfile: dest=/home/vagrant/.bashrc regexp="NVM_DIR=" line="export NVM_DIR=/home/vagrant/.nvm" backup=yes

- lineinfile: dest=/home/vagrant/.bashrc regexp="$NVM_DIR/" line="[ -s $NVM_DIR/nvm.sh ] && . $NVM_DIR/nvm.sh" backup=yes

- name: create simlink to nvm
  file:
    src: /home/vagrant/.nvm/nvm.sh
    dest: /usr/bin/nvm
    state: link

- shell: /home/vagrant/.nvm/nvm.sh

- shell: nvm install 0.10.33 chdir=/home/vagrant/.nvm
- shell: nvm alias default 0.10.33 chdir=/home/vagrant/.nvm
- shell: nvm use default chdir=/home/vagrant/.nvm

#- shell: npm install npm -g chdir=/home/vagrant/.nvm